apiVersion: v1
kind: Pod
metadata:
  name: react-app-pod
  labels:
    app: react-app
spec:
   containers:
    - name: react-app
      image: reactapp2
      imagePullPolicy: Never
      ports:
       - containerPort: 3000
 